# Generated by Django 6.0.2 on 2026-02-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='content_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
