# Generated by Django 6.0.2 on 2026-02-26 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_create_visibility_levels'),
        ('reports', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_date',
        ),
        migrations.AddField(
            model_name='report',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='visibility_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='access_control.visibilitylevel'),
        ),
    ]
