# Generated by Django 6.0.2 on 2026-02-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_options_remove_report_report_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
    ]
