# Generated by Django 6.0.2 on 2026-03-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_reporttype_report_approved_by_report_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
    ]
