# Generated by Django 6.0.2 on 2026-02-17 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0002_create_visibility_levels'),
        ('departments', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department'),
        ),
        migrations.AddField(
            model_name='document',
            name='visibility_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.visibilitylevel'),
        ),
    ]
