# Generated by Django 6.0.2 on 2026-03-04 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
